### ISSUE TITLE
License of the BASE-search metadata

### ISSUE THREAD

**Issue by shigapov** [cbroschinski/MALIS-21-Master_Thesis#1]
Hi @cbroschinski, thank you for sharing your work!

What is the license of [base_dump](https://github.com/cbroschinski/MALIS-21-Master_Thesis/tree/master/data/base_dump)? Can I reuse it for training a classifier?

**Comment by cbroschinski** [comment]
The data is now officially [licensed](https://github.com/cbroschinski/MALIS-21-Master_Thesis/blob/master/data/base_dump/LICENSE.md) under the ODbL, so feel free to use  it. However, using it as a standalone set for ML training is probably not the best idea as the corpus is likely too small. The license file has some more hints on this.

**Comment by renat-kaufmann** [comment]
Thank you!

> While the records can be used to bootstrap and train an Annif backend, the training set is too small to obtain a good classificator for DDC classes. If you are interested in re-using the code with a suitable training set, you might want to get in contact with [BASE](http://oai.base-search.net/#alternatives) and ask for the latest BASE dump.

I've actually contacted the BASE-Team via an online form, but have not received an answer. Then I've asked a question about a training data for a DDC-classifier at https://metadaten.community/t/datensatz-mit-ddc-annotationen/429, and that's how I learned about your work.
